vava_db_dir = '.' #'/mnt/c/Users/MSI/Variant_Vault/_pipeline'
database_file = 'TSHCvar.db'
database_file_brcas = 'BRCASvar_v2.db'
variant_table = 'db_var'
version_history_table = 'db_var_version_history'